<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('orders', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->string('order_number')->unique();
            $table->foreignUlid('user_id')->constrained('users'); // Cashier
            $table->foreignUlid('customer_id')->nullable()->constrained('customers')->nullOnDelete(); // Member
            
            // Financials
            $table->decimal('subtotal', 12, 2)->default(0);
            $table->decimal('tax_amount', 12, 2)->default(0);
            $table->decimal('discount_amount', 12, 2)->default(0);
            $table->decimal('grand_total', 12, 2)->default(0);
            
            // Meta & Status
            $table->string('payment_method'); // 'cash', 'qris', ...
            $table->string('payment_status')->default('pending'); // 'pending', 'paid', 'failed'
            $table->string('order_status')->default('pending'); // 'pending', 'preparing', ...
            $table->string('order_type')->default('dine_in'); // 'dine_in', 'takeaway'
            
            // Sync & Offline
            $table->string('offline_id')->nullable()->unique(); // UUID generated by PWA
            $table->timestamp('synced_at')->nullable();
            
            $table->softDeletes();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('orders');
    }
};
